/**
 * Figures for three /learn/concepts pages:
 *
 *   evaluating-a-board  — what the fair leaf evaluator looks at, x-rayed on a
 *                         real position, and two look-alike boards whose
 *                         futures differ;
 *   survival-vs-score   — one complete toy game as a timeline, its flow
 *                         balance, and where its points came from;
 *   heavy-tails         — the per-game scores of a retained 64-game fair-D4
 *                         cohort, and what a mean over a few games can hide.
 *
 * Data sources, all generated by scripts under web/scripts/ and written under
 * web/content/learn/data/:
 *
 *   leaf-scenarios.json    generate-leaf-scenarios.ts  (TypeScript engine)
 *   sample-game.json       generate-sample-game.ts     (TypeScript engine)
 *   d4-cohort-scores.json  extract-d4-cohort.ts        (snapshot of a retained
 *                          run; see docs/exploratory/finding-01-score-is-survival.md)
 *
 * No component computes or infers a research number. Recorded figures are
 * either read verbatim from those files or passed in as props by the MDX page,
 * which cites the record they come from. Every figure is a server component:
 * plain SVG with SMIL for decorative sequencing only, so the explanation never
 * depends on motion, and CSS motion stops under prefers-reduced-motion
 * (globals.css).
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { CellGlyph } from "./Board";
import { MiniBoard } from "./Engine";

const INK = "#fafafa";
const INK_2 = "#a1a1aa";
const INK_3 = "#71717a";
const GRID = "#27272a";
const BLUE = "#3987e5";
const ORANGE = "#d95926";
const AQUA = "#199e70";
const ACCENT = "#facc15";
const FONT = "system-ui, -apple-system, 'Segoe UI', sans-serif";

/** Displays a recorded figure without inflating it: integers stay exact, and a
 * fractional value keeps two decimals rather than being rounded to a whole. */
function fmt(n: number): string {
  return n.toLocaleString("en-US", { maximumFractionDigits: 2 });
}

function fmt1(n: number): string {
  return n.toFixed(1);
}

/** Greedy word wrap for SVG text, which does not wrap on its own. */
function wrap(text: string, chars: number, maxLines = 2): string[] {
  const words = text.split(" ");
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    const candidate = line ? `${line} ${word}` : word;
    if (candidate.length <= chars) {
      line = candidate;
      continue;
    }
    lines.push(line);
    line = word;
    if (lines.length === maxLines) break;
  }
  if (lines.length < maxLines && line) lines.push(line);
  return lines;
}

function Missing({ what, script }: { what: string; script: string }) {
  return (
    <div className="engine-fig" style={{ color: INK_3, fontSize: 13 }}>
      {what} is not available in this checkout. Run <code>{script}</code> from{" "}
      <code>web/</code> to regenerate it.
    </div>
  );
}

function dataPath(file: string): string {
  return join(process.cwd(), "content", "learn", "data", file);
}

function loadJson<T>(file: string): T | null {
  const path = dataPath(file);
  if (!existsSync(path)) return null;
  return JSON.parse(readFileSync(path, "utf8")) as T;
}

/* =========================================================================
 * Shared shapes of the generated data.
 * ========================================================================= */

interface Annotated {
  board: string;
  heights: number[];
  maxHeight: number;
  dangerHeight: number;
  occupied: number;
  solid: number[];
  cracked: number[];
  numbered: number[];
  oneDrop: number[];
  selfClearColumns: number[];
  triggers: { column: number; discs: number[] }[];
  overRun: number[];
  risePoppers: number;
  riseBlocked: boolean;
}

interface LeafScenarios {
  xray: Annotated & { nextDisc: number; movesUntilRise: number; origin: string };
  pair: {
    rollout: { policy: string; tapes: number; moveCap: number };
    paired: { wins: number; ties: number; losses: number };
    better: Annotated & { future: Future };
    worse: Annotated & { future: Future };
  };
}

interface Future {
  tapes: number;
  meanMoves: number;
  meanScore: number;
  minMoves: number;
  maxMoves: number;
  moves: number[];
  scores: number[];
}

interface SampleGame {
  seedHex: string;
  latentSeedHex: string;
  policy: { name: string; rule: string };
  summary: {
    moves: number;
    score: number;
    rises: number;
    boardClears: number;
    levelPoints: number;
    chainPoints: number;
    pointsPerMove: number;
    clears: number;
    reveals: number;
    clearsPerMove: number;
    revealsPerMove: number;
    ending: string;
    finalBoard: string;
  };
  history: {
    move: number;
    disc: number;
    column: number;
    points: number;
    score: number;
    board: string;
    maxHeight: number;
    occupied: number;
    clears: number;
    reveals: number;
    maxWaveDepth: number;
    rise: boolean;
    movesUntilRise: number;
    gameOver: boolean;
  }[];
}

interface Cohort {
  source: string;
  finding: string;
  policy: string;
  seedLease: string;
  games: number;
  moveCap: number;
  censoredGames: number;
  score: { mean: number; median: number; q25: number; min: number; max: number; sd: number };
  moves: { mean: number; median: number; q25: number; min: number; max: number };
  decomposition: {
    levelPointsTotal: number;
    clearPointsTotal: number;
    chainPointsTotal: number;
    scoreTotal: number;
    levelShare: number;
    clearShare: number;
    chainShare: number;
  } | null;
  games_detail: { seedHex: string; score: number; moves: number; censored: boolean }[];
}

/* =========================================================================
 * 1. The leaf evaluator, x-rayed on a real position.
 * ========================================================================= */

export function LeafXray({ caption }: { caption?: string }) {
  const data = loadJson<LeafScenarios>("leaf-scenarios.json");
  if (!data) {
    return <Missing what="The x-rayed position" script="node --experimental-strip-types scripts/generate-leaf-scenarios.ts" />;
  }
  const x = data.xray;
  const s = 34;
  const boardW = 7 * s;
  const W = 760;
  const H = 7 * s + 150;
  const covered = x.solid.length + x.cracked.length;
  const rows: { color: string; title: string; body: string }[] = [
    {
      color: BLUE,
      title: `Column heights ${x.heights.join(" ")}`,
      body: `The tallest column holds ${x.maxHeight} discs — ${x.dangerHeight} above the height of four where the evaluator starts charging a steep penalty.`,
    },
    {
      color: ORANGE,
      title: `${x.movesUntilRise} move${x.movesUntilRise === 1 ? "" : "s"} until the board rises`,
      body: "The same board is safe with five moves of room and dangerous with one. Height alone cannot say which.",
    },
    {
      color: INK_2,
      title: `${covered} covered discs (${x.solid.length} solid, ${x.cracked.length} cracked)`,
      body: "Numbers the player cannot read. A cracked disc is one hit from turning back into a useful number; a solid one needs two.",
    },
    {
      color: ACCENT,
      title: `${x.oneDrop.length} disc${x.oneDrop.length === 1 ? "" : "s"} one drop from clearing`,
      body: "Ringed below. Some single legal drop makes each of these clear immediately — the board is holding live triggers.",
    },
    {
      color: AQUA,
      title: `${x.risePoppers} disc${x.risePoppers === 1 ? "" : "s"} would clear if the board rose now`,
      body: "Pushing everything up one row changes every vertical run. A board can be one rise away from a free cascade, or from nothing.",
    },
    {
      color: ORANGE,
      title: `${x.overRun.length} disc${x.overRun.length === 1 ? "" : "s"} stuck in runs longer than their own number`,
      body: "A disc whose row and column are both already too long cannot clear where it stands. It is dead weight until the shape around it changes.",
    },
  ];
  return (
    <figure className="engine-fig">
      <svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="A real position annotated with what a leaf evaluator measures">
        <text y={12} fontSize={12.5} fontFamily={FONT} fontWeight={700} fill={INK}>
          One real position, and the kinds of thing an evaluator counts on it
        </text>
        <text y={28} fontSize={10.5} fontFamily={FONT} fill={INK_3}>
          {`board from ${x.origin}; every annotation recomputed with the engine, not with the evaluator`}
        </text>

        <g transform="translate(0 40)">
          <MiniBoard cells={x.board} s={s} highlight={x.oneDrop} />
          {/* covered cells get a slate outline so the covered mass is visible at a glance */}
          {[...x.solid, ...x.cracked].map((index) => (
            <rect
              key={`c${index}`}
              x={(index % 7) * s + 3}
              y={Math.floor(index / 7) * s + 3}
              width={s - 6}
              height={s - 6}
              rx={s * 0.12}
              fill="none"
              stroke={INK_3}
              strokeWidth={1}
              strokeDasharray="3 3"
            />
          ))}
          {/* the pulse is decoration; the rings above carry the same information */}
          <g className="engine-motion">
            {x.oneDrop.map((index, i) => (
              <circle
                key={`p${index}`}
                cx={(index % 7) * s + s / 2}
                cy={Math.floor(index / 7) * s + s / 2}
                r={s * 0.5}
                fill="none"
                stroke={ACCENT}
                strokeWidth={2}
                opacity={0}
              >
                <animate
                  attributeName="opacity"
                  values="0;0.9;0"
                  dur="2.4s"
                  begin={`${i * 0.4}s`}
                  repeatCount="indefinite"
                />
              </circle>
            ))}
          </g>
          {/* height bars under the board */}
          {x.heights.map((height, column) => (
            <g key={`h${column}`} transform={`translate(${column * s} ${7 * s + 8})`}>
              <rect x={s * 0.2} y={0} width={s * 0.6} height={12} rx={3} fill="#1f1f23" />
              <rect x={s * 0.2} y={0} width={(s * 0.6 * height) / 7} height={12} rx={3} fill={BLUE} />
              <text x={s / 2} y={26} textAnchor="middle" fontSize={10} fontFamily={FONT} fill={INK_2}>
                {height}
              </text>
            </g>
          ))}
          <text x={0} y={7 * s + 48} fontSize={10} fontFamily={FONT} fill={INK_3}>
            {`heights · next disc`}
          </text>
          <g transform={`translate(96 ${7 * s + 36})`}>
            <CellGlyph cell={x.nextDisc} x={0} y={0} s={16} />
          </g>
        </g>

        <g transform={`translate(${boardW + 34} 44)`}>
          {rows.map((row, i) => (
            <g key={row.title} transform={`translate(0 ${i * 52})`}>
              <rect x={0} y={0} width={4} height={40} rx={2} fill={row.color} />
              <text x={12} y={11} fontSize={11.5} fontFamily={FONT} fontWeight={700} fill={INK}>
                {row.title}
              </text>
              {wrap(row.body, 74).map((line, k) => (
                <text key={k} x={12} y={26 + k * 13} fontSize={10.5} fontFamily={FONT} fill={INK_2}>
                  {line}
                </text>
              ))}
            </g>
          ))}
        </g>
      </svg>
      <details className="engine-table">
        <summary>table view — what each column offers</summary>
        <table>
          <thead>
            <tr>
              <th>column</th>
              <th>height</th>
              <th>discs that clear something if dropped here</th>
            </tr>
          </thead>
          <tbody>
            {x.heights.map((height, column) => {
              const trigger = x.triggers.find((t) => t.column === column);
              return (
                <tr key={column}>
                  <td>{column}</td>
                  <td>{height}</td>
                  <td>{trigger ? trigger.discs.join(", ") : "none"}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </details>
      {caption && <figcaption>{caption}</figcaption>}
    </figure>
  );
}

/* =========================================================================
 * 2. The terms that survive in the fair leaf, and which way each one pulls.
 * ========================================================================= */

/**
 * The structure of the reference leaf, read from
 * approaches/fair-expectimax/reference/fair-only-horizon.cpp (the `fairLeaf`
 * dot product) and grouped by the stages that
 * docs/exploratory/finding-13-fast-engine.md §3.2 measures. Only the direction
 * of each term is shown: a weight is a tuning constant, not a research result,
 * and no number from it is quoted here.
 */
const LEAF_STAGES: { stage: string; terms: { name: string; good: boolean; plain: string }[] }[] = [
  {
    stage: "heights, rise pressure, danger height",
    terms: [
      { name: "open columns", good: true, plain: "columns still free to receive a disc" },
      { name: "height load", good: false, plain: "discs weighted by how high they sit" },
      { name: "rise pressure", good: false, plain: "tall columns, counted more heavily as the rise approaches" },
      { name: "danger height", good: false, plain: "how far the tallest column climbs above four" },
    ],
  },
  {
    stage: "per-cell sweep: direct potential, covered and low-number risk",
    terms: [
      { name: "direct potential", good: true, plain: "discs that one added neighbour would clear" },
      { name: "next-disc vertical options", good: true, plain: "columns where the visible disc would clear on landing" },
      { name: "solid and cracked cells", good: false, plain: "how much of the board is unreadable" },
      { name: "numbered cells", good: false, plain: "how full the board is with live discs" },
      { name: "covered height risk", good: false, plain: "covered discs carried high, worse at the edges" },
      { name: "low-number height risk", good: false, plain: "ones and twos stranded high up" },
      { name: "high low numbers", good: false, plain: "the same idea, counted as a plain tally" },
    ],
  },
  {
    stage: "release inventory",
    terms: [
      { name: "latent chain potential", good: true, plain: "discs that would clear once a neighbour goes first" },
    ],
  },
  {
    stage: "adjacent ones",
    terms: [
      { name: "adjacent ones", good: false, plain: "two 1s side by side, each blocking the other from ever being alone" },
    ],
  },
  {
    stage: "runs of twos",
    terms: [
      { name: "runs of twos", good: false, plain: "three or more 2s in a line, which can no longer make a run of two" },
      { name: "dead low numbers", good: false, plain: "low discs with no route back to clearing" },
    ],
  },
  {
    stage: "cover exposure",
    terms: [
      { name: "cracked exposure", good: true, plain: "cracked discs a nearby clear would finish revealing" },
      { name: "solid exposure", good: true, plain: "solid discs a nearby clear would start opening" },
    ],
  },
];

export function LeafTerms({ caption }: { caption?: string }) {
  const W = 760;
  const rowH = 15;
  const stageGap = 12;
  const layout: { group: (typeof LEAF_STAGES)[number]; top: number }[] = [];
  let cursor = 46;
  for (const group of LEAF_STAGES) {
    layout.push({ group, top: cursor });
    cursor += 16 + group.terms.length * rowH + stageGap;
  }
  const H = cursor + 10;
  return (
    <figure className="engine-fig">
      <svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="The terms the fair leaf evaluator adds up">
        <text y={13} fontSize={12.5} fontFamily={FONT} fontWeight={700} fill={INK}>
          What the reference evaluator adds up, and which way each term pulls
        </text>
        <text y={30} fontSize={10.5} fontFamily={FONT} fill={INK_3}>
          grouped by the six stages of the leaf; green raises the score of a board, orange lowers it
        </text>
        {layout.map(({ group, top }) => (
          <g key={group.stage} transform={`translate(0 ${top})`}>
            <path d={`M0,0 H${W - 8}`} stroke={GRID} />
            <text y={12} fontSize={10.5} fontFamily={FONT} fill={INK_3}>
              {group.stage}
            </text>
            {group.terms.map((term, i) => (
              <g key={term.name} transform={`translate(0 ${16 + i * rowH})`}>
                <circle cx={6} cy={7} r={4} fill={term.good ? AQUA : ORANGE} />
                <text x={18} y={10.5} fontSize={11} fontFamily={FONT} fontWeight={600} fill={INK}>
                  {term.name}
                </text>
                <text x={210} y={10.5} fontSize={11} fontFamily={FONT} fill={INK_2}>
                  {term.plain}
                </text>
              </g>
            ))}
          </g>
        ))}
      </svg>
      {caption && <figcaption>{caption}</figcaption>}
    </figure>
  );
}

/* =========================================================================
 * 3. Two boards with the same summary and different futures.
 * ========================================================================= */

export function BoardLookalikes({ caption }: { caption?: string }) {
  const data = loadJson<LeafScenarios>("leaf-scenarios.json");
  if (!data) {
    return <Missing what="The look-alike boards" script="node --experimental-strip-types scripts/generate-leaf-scenarios.ts" />;
  }
  const { better, worse, rollout, paired } = data.pair;
  const s = 30;
  const W = 760;
  const H = 7 * s + 190;
  const maxMoves = Math.max(better.future.meanMoves, worse.future.meanMoves);
  const barW = 190;
  const panels = [
    { key: "A", board: better, tone: AQUA },
    { key: "B", board: worse, tone: ORANGE },
  ];
  const sameness = [
    `column heights ${better.heights.join(" ")}`,
    `${better.solid.length} solid and ${better.cracked.length} cracked covered discs`,
    `the same three numbered discs`,
    `${better.oneDrop.length} discs one drop from clearing`,
    `${better.risePoppers} discs set off by an immediate rise`,
  ];
  return (
    <figure className="engine-fig">
      <svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Two boards with identical summaries and different futures">
        <text y={13} fontSize={12.5} fontFamily={FONT} fontWeight={700} fill={INK}>
          Same summary, different future
        </text>
        {panels.map((panel, i) => (
          <g key={panel.key} transform={`translate(${i * (7 * s + 26)} 26)`}>
            <text y={11} fontSize={11} fontFamily={FONT} fontWeight={700} fill={panel.tone}>
              {`board ${panel.key}`}
            </text>
            <MiniBoard cells={panel.board.board} y={18} s={s} />
          </g>
        ))}
        <g transform={`translate(${2 * (7 * s + 26) + 8} 26)`}>
          <text y={11} fontSize={11} fontFamily={FONT} fontWeight={700} fill={INK}>
            Identical on every static summary:
          </text>
          {sameness.map((line, i) => (
            <g key={line} transform={`translate(0 ${22 + i * 17})`}>
              <circle cx={4} cy={-3} r={2.5} fill={INK_3} />
              <text x={14} y={0} fontSize={11} fontFamily={FONT} fill={INK_2}>
                {line}
              </text>
            </g>
          ))}
          <text y={122} fontSize={11} fontFamily={FONT} fill={INK_3}>
            {`They differ only in where the same discs sit.`}
          </text>
        </g>

        <g transform={`translate(0 ${7 * s + 56})`}>
          <path d={`M0,0 H${W - 8}`} stroke={GRID} />
          <text y={20} fontSize={11.5} fontFamily={FONT} fontWeight={700} fill={INK}>
            {`Played forward from each board with the same ${rollout.tapes} scripted disc tapes and the same toy policy`}
          </text>
          {panels.map((panel, i) => {
            const f = panel.board.future;
            const w = (f.meanMoves / maxMoves) * barW;
            return (
              <g key={panel.key} transform={`translate(0 ${34 + i * 30})`}>
                <text x={0} y={12} fontSize={11} fontFamily={FONT} fill={INK_2}>
                  {`board ${panel.key}`}
                </text>
                <rect x={60} y={2} width={barW} height={14} rx={4} fill="#1f1f23" />
                <rect x={60} y={2} width={w} height={14} rx={4} fill={panel.tone} />
                <text x={60 + barW + 10} y={13} fontSize={11.5} fontFamily={FONT} fontWeight={700} fill={INK}>
                  {`${fmt1(f.meanMoves)} moves on average`}
                </text>
                <text x={60 + barW + 172} y={13} fontSize={10.5} fontFamily={FONT} fill={INK_3}>
                  {`shortest ${f.minMoves}, longest ${f.maxMoves} · mean score ${fmt(f.meanScore)}`}
                </text>
              </g>
            );
          })}
          <text y={110} fontSize={11} fontFamily={FONT} fill={INK_2}>
            {`Tape by tape: board A lasted longer in ${paired.wins}, the same in ${paired.ties}, and shorter in ${paired.losses} of the ${rollout.tapes} replays.`}
          </text>
          <text y={128} fontSize={10.5} fontFamily={FONT} fill={INK_3}>
            {`A demonstration with a toy policy on ${rollout.tapes} scripted tapes, not a research measurement.`}
          </text>
        </g>
      </svg>
      <details className="engine-table">
        <summary>table view — lifetime under each tape</summary>
        <table>
          <thead>
            <tr>
              <th>tape</th>
              <th>board A moves</th>
              <th>board B moves</th>
            </tr>
          </thead>
          <tbody>
            {better.future.moves.map((moves, i) => (
              <tr key={i}>
                <td>{i + 1}</td>
                <td>{moves}</td>
                <td>{worse.future.moves[i]}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </details>
      {caption && <figcaption>{caption}</figcaption>}
    </figure>
  );
}

/* =========================================================================
 * 4. One complete game as a timeline.
 * ========================================================================= */

export function GameTimeline({ caption }: { caption?: string }) {
  const game = loadJson<SampleGame>("sample-game.json");
  if (!game) {
    return <Missing what="The sample game" script="node --experimental-strip-types scripts/generate-sample-game.ts" />;
  }
  const history = game.history;
  const W = 760;
  const plotH = 150;
  const H = plotH + 130;
  const left = 34;
  const right = 58;
  const plotW = W - left - right;
  const n = history.length;
  const xOf = (move: number) => left + ((move - 1) / Math.max(1, n - 1)) * plotW;
  const maxScore = game.summary.score;
  const yHeight = (h: number) => 26 + plotH - (h / 7) * plotH;
  const yScore = (score: number) => 26 + plotH - (score / maxScore) * plotH;

  const heightPath = history.map((m, i) => `${i === 0 ? "M" : "L"}${xOf(m.move).toFixed(1)},${yHeight(m.maxHeight).toFixed(1)}`).join(" ");
  const scorePath = history.map((m, i) => `${i === 0 ? "M" : "L"}${xOf(m.move).toFixed(1)},${yScore(m.score).toFixed(1)}`).join(" ");
  const rises = history.filter((m) => m.rise);
  const last = history[history.length - 1];

  return (
    <figure className="engine-fig">
      <svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="One complete game: board height and score over time">
        <text y={12} fontSize={12.5} fontFamily={FONT} fontWeight={700} fill={INK}>
          {`One complete game, move by move — ${game.summary.moves} moves, ${fmt(game.summary.score)} points`}
        </text>

        {/* height axis */}
        {[0, 2, 4, 6].map((h) => (
          <g key={h}>
            <path d={`M${left},${yHeight(h)} H${left + plotW}`} stroke={GRID} strokeWidth={1} />
            <text x={left - 6} y={yHeight(h)} textAnchor="end" dominantBaseline="central" fontSize={9.5} fontFamily={FONT} fill={INK_3}>
              {h}
            </text>
          </g>
        ))}
        <text x={0} y={20} fontSize={9.5} fontFamily={FONT} fill={BLUE}>
          rows
        </text>

        {/* rise markers */}
        {rises.map((m) => (
          <g key={`r${m.move}`}>
            <path d={`M${xOf(m.move)},26 V${26 + plotH}`} stroke={AQUA} strokeWidth={1} strokeDasharray="2 3" opacity={0.8} />
            <text x={xOf(m.move)} y={22} textAnchor="middle" fontSize={9} fontFamily={FONT} fill={AQUA}>
              rise
            </text>
          </g>
        ))}

        {/* the two series */}
        <path d={scorePath} fill="none" stroke={ACCENT} strokeWidth={2} />
        <path d={heightPath} fill="none" stroke={BLUE} strokeWidth={2} />
        {history.map((m) => (
          <circle key={`d${m.move}`} cx={xOf(m.move)} cy={yHeight(m.maxHeight)} r={2} fill={BLUE} />
        ))}

        {/* score axis on the right */}
        <text x={left + plotW + 6} y={yScore(maxScore)} dominantBaseline="central" fontSize={9.5} fontFamily={FONT} fill={ACCENT}>
          {fmt(maxScore)}
        </text>
        <text x={left + plotW + 6} y={yScore(0)} dominantBaseline="central" fontSize={9.5} fontFamily={FONT} fill={INK_3}>
          0
        </text>

        {/* the end */}
        <circle cx={xOf(last.move)} cy={yHeight(last.maxHeight)} r={5} fill={ORANGE} />
        <text x={left + plotW} y={26 + plotH + 30} textAnchor="end" fontSize={11} fontFamily={FONT} fontWeight={700} fill={ORANGE}>
          {game.summary.ending === "no-room-to-rise"
            ? "game over: a disc was in the top row, so the board could not rise"
            : "game over: no column was open"}
        </text>
        <text x={left} y={26 + plotH + 16} fontSize={10} fontFamily={FONT} fill={INK_3}>
          move 1
        </text>
        <text x={left + plotW} y={26 + plotH + 16} textAnchor="end" fontSize={10} fontFamily={FONT} fill={INK_3}>
          {`move ${last.move}`}
        </text>

        <g transform={`translate(${left} ${26 + plotH + 48})`}>
          <rect width={12} height={3} y={4} fill={BLUE} />
          <text x={18} y={9} fontSize={10.5} fontFamily={FONT} fill={INK_2}>
            tallest column, in rows
          </text>
          <rect x={170} width={12} height={3} y={4} fill={ACCENT} />
          <text x={188} y={9} fontSize={10.5} fontFamily={FONT} fill={INK_2}>
            score so far
          </text>
          <rect x={320} width={12} height={3} y={4} fill={AQUA} />
          <text x={338} y={9} fontSize={10.5} fontFamily={FONT} fill={INK_2}>
            {`row rise (${game.summary.rises} of them, +17,000 points each)`}
          </text>
        </g>
        <text x={left} y={26 + plotH + 76} fontSize={10.5} fontFamily={FONT} fill={INK_3}>
          {`The score line is a staircase: it steps at every rise and barely moves between them.`}
        </text>
      </svg>
      <details className="engine-table">
        <summary>table view — every rise, and the last move</summary>
        <table>
          <thead>
            <tr>
              <th>move</th>
              <th>points</th>
              <th>score</th>
              <th>tallest column</th>
              <th>discs on board</th>
            </tr>
          </thead>
          <tbody>
            {[...rises, last].map((m, i) => (
              <tr key={`${m.move}-${i}`}>
                <td>{m.move}{m.rise ? " (rise)" : " (last)"}</td>
                <td>{fmt(m.points)}</td>
                <td>{fmt(m.score)}</td>
                <td>{m.maxHeight}</td>
                <td>{m.occupied}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </details>
      {caption && <figcaption>{caption}</figcaption>}
    </figure>
  );
}

/* =========================================================================
 * 5. Flow balance: clears and reveals per move against the recorded targets.
 * ========================================================================= */

export function FlowBalance({
  targetClears,
  targetReveals,
  referenceLabel,
  referenceClears,
  referenceReveals,
  caption,
}: {
  /** The recorded diagnostic target, quoted by the page from a retained record. */
  targetClears: number;
  targetReveals: number;
  /** A recorded reference policy measurement, quoted by the page. */
  referenceLabel: string;
  referenceClears: number;
  referenceReveals: number;
  caption?: string;
}) {
  const game = loadJson<SampleGame>("sample-game.json");
  if (!game) {
    return <Missing what="The sample game" script="node --experimental-strip-types scripts/generate-sample-game.ts" />;
  }
  const W = 760;
  const H = 210;
  const left = 196;
  const barW = 376;
  const scale = Math.max(targetClears, targetReveals, referenceClears, referenceReveals, game.summary.clearsPerMove, game.summary.revealsPerMove) * 1.15;
  const panels = [
    {
      title: "numbered discs cleared per move",
      target: targetClears,
      rows: [
        { label: referenceLabel, value: referenceClears, tone: BLUE },
        { label: "the toy game above", value: game.summary.clearsPerMove, tone: INK_3 },
      ],
    },
    {
      title: "covered discs revealed per move",
      target: targetReveals,
      rows: [
        { label: referenceLabel, value: referenceReveals, tone: BLUE },
        { label: "the toy game above", value: game.summary.revealsPerMove, tone: INK_3 },
      ],
    },
  ];
  return (
    <figure className="engine-fig">
      <svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Clears and reveals per move against the recorded diagnostic targets">
        {panels.map((panel, p) => (
          <g key={panel.title} transform={`translate(0 ${10 + p * 100})`}>
            <text y={10} fontSize={11.5} fontFamily={FONT} fontWeight={700} fill={INK}>
              {panel.title}
            </text>
            {panel.rows.map((row, i) => {
              const w = (row.value / scale) * barW;
              return (
                <g key={row.label} transform={`translate(0 ${20 + i * 24})`}>
                  <text x={left - 8} y={11} textAnchor="end" fontSize={10.5} fontFamily={FONT} fill={INK_2}>
                    {row.label}
                  </text>
                  <rect x={left} y={2} width={barW} height={14} rx={4} fill="#1f1f23" />
                  <rect x={left} y={2} width={w} height={14} rx={4} fill={row.tone} />
                  <text x={left + w + 8} y={13} fontSize={11} fontFamily={FONT} fontWeight={700} fill={INK}>
                    {row.value.toFixed(2)}
                  </text>
                </g>
              );
            })}
            <g transform={`translate(${left + (panel.target / scale) * barW} 14)`}>
              <path d="M0,0 V56" stroke={ACCENT} strokeWidth={2} strokeDasharray="3 3" />
              <text x={4} y={68} fontSize={10.5} fontFamily={FONT} fontWeight={700} fill={ACCENT}>
                {`${panel.target} — the break-even rate`}
              </text>
            </g>
          </g>
        ))}
      </svg>
      {caption && <figcaption>{caption}</figcaption>}
    </figure>
  );
}

/* =========================================================================
 * 6. Where the points came from.
 * ========================================================================= */

export function ScoreSources({ caption }: { caption?: string }) {
  const game = loadJson<SampleGame>("sample-game.json");
  const cohort = loadJson<Cohort>("d4-cohort-scores.json");
  if (!game) {
    return <Missing what="The sample game" script="node --experimental-strip-types scripts/generate-sample-game.ts" />;
  }
  // Shares for the cohort row are the ones recorded in the run file; the toy
  // game's shares come from its own generated totals.
  const bars: { label: string; sub: string; level: number; chain: number; clear: number }[] = [
    {
      label: "the toy game on this page",
      sub: `${game.summary.moves} moves, one game`,
      level: game.summary.levelPoints / game.summary.score,
      chain: game.summary.chainPoints / game.summary.score,
      clear: 0,
    },
  ];
  if (cohort?.decomposition) {
    const d = cohort.decomposition;
    bars.push({
      label: `${cohort.policy}, ${cohort.games} games`,
      sub: `${cohort.finding.split("/").pop()}`,
      level: d.levelShare,
      chain: d.chainShare,
      clear: d.clearShare,
    });
  }
  const W = 760;
  const H = 60 + bars.length * 62;
  const left = 200;
  const barW = 480;
  return (
    <figure className="engine-fig">
      <svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Where the points in a Drop7 game come from">
        <text y={12} fontSize={12.5} fontFamily={FONT} fontWeight={700} fill={INK}>
          Where the points come from
        </text>
        {bars.map((bar, i) => {
          const levelW = bar.level * barW;
          const chainW = bar.chain * barW;
          const clearW = bar.clear * barW;
          const pct = (value: number) => `${(value * 100).toFixed(1)}%`;
          return (
            <g key={bar.label} transform={`translate(0 ${34 + i * 62})`}>
              <text x={left - 10} y={13} textAnchor="end" fontSize={11} fontFamily={FONT} fontWeight={600} fill={INK}>
                {bar.label}
              </text>
              <text x={left - 10} y={28} textAnchor="end" fontSize={10} fontFamily={FONT} fill={INK_3}>
                {bar.sub}
              </text>
              <rect x={left} y={2} width={barW} height={20} rx={4} fill="#1f1f23" />
              <rect x={left} y={2} width={levelW} height={20} rx={4} fill={AQUA} />
              <rect x={left + levelW} y={2} width={Math.max(chainW, 1)} height={20} fill={ORANGE} />
              {clearW > 0 && <rect x={left + levelW + chainW} y={2} width={clearW} height={20} fill={BLUE} />}
              <text x={left + 8} y={16} fontSize={10.5} fontFamily={FONT} fontWeight={700} fill="#052e1c">
                {`row rises ${pct(bar.level)}`}
              </text>
              <text x={left + barW} y={38} textAnchor="end" fontSize={10.5} fontFamily={FONT} fill={ORANGE}>
                {`chain waves ${pct(bar.chain)} · board clears ${pct(bar.clear)}`}
              </text>
            </g>
          );
        })}
      </svg>
      {caption && <figcaption>{caption}</figcaption>}
    </figure>
  );
}

/* =========================================================================
 * 7. Every game in a retained cohort, as one dot each.
 * ========================================================================= */

export function ScoreStrip({ caption }: { caption?: string }) {
  const cohort = loadJson<Cohort>("d4-cohort-scores.json");
  if (!cohort) {
    return <Missing what="The per-game cohort scores" script="node --experimental-strip-types scripts/extract-d4-cohort.ts" />;
  }
  const games = [...cohort.games_detail].sort((a, b) => a.score - b.score);
  const W = 760;
  const H = 260;
  const left = 20;
  const right = 20;
  const plotW = W - left - right;
  const top = 76;
  const stripH = 90;
  const scale = 1_100_000;
  const xOf = (score: number) => left + (score / scale) * plotW;
  // A dot per game, stacked when two games land on nearly the same score.
  const buckets = new Map<number, number>();
  const dots = games.map((game) => {
    const bucket = Math.round(xOf(game.score) / 7);
    const level = buckets.get(bucket) ?? 0;
    buckets.set(bucket, level + 1);
    return { game, x: xOf(game.score), level };
  });
  const ticks = [0, 250_000, 500_000, 750_000, 1_000_000];
  return (
    <figure className="engine-fig">
      <svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Every game in the cohort as one dot">
        <text y={12} fontSize={12.5} fontFamily={FONT} fontWeight={700} fill={INK}>
          {`${cohort.games} games of ${cohort.policy}, one dot each`}
        </text>
        <text y={26} fontSize={10} fontFamily={FONT} fill={INK_3}>
          {`${cohort.source} · development cohort, ${cohort.censoredGames} games censored at the ${fmt(cohort.moveCap)}-move cap`}
        </text>
        <text y={39} fontSize={10} fontFamily={FONT} fill={INK_3}>
          {cohort.finding}
        </text>

        {ticks.map((tick) => (
          <g key={tick}>
            <path d={`M${xOf(tick)},${top} V${top + stripH + 8}`} stroke={GRID} />
            <text x={xOf(tick)} y={top + stripH + 24} textAnchor="middle" fontSize={10} fontFamily={FONT} fill={INK_3}>
              {tick === 0 ? "0" : `${tick / 1000}k`}
            </text>
          </g>
        ))}

        {dots.map(({ game, x, level }) => (
          <circle
            key={game.seedHex}
            cx={x}
            cy={top + stripH - 8 - level * 9}
            r={4}
            fill={game.score >= 1_000_000 ? ACCENT : BLUE}
            opacity={0.85}
          >
            <title>{`${game.seedHex}: ${fmt(game.score)} points in ${game.moves} moves`}</title>
          </circle>
        ))}

        {/* median and mean */}
        <g>
          <path d={`M${xOf(cohort.score.median)},${top - 22} V${top + stripH + 6}`} stroke={AQUA} strokeWidth={2} />
          <text x={xOf(cohort.score.median)} y={top - 26} textAnchor="middle" fontSize={10.5} fontFamily={FONT} fontWeight={700} fill={AQUA}>
            {`median ${fmt(cohort.score.median)}`}
          </text>
        </g>
        <g>
          <path d={`M${xOf(cohort.score.mean)},${top - 6} V${top + stripH + 6}`} stroke={ORANGE} strokeWidth={2} />
          <text x={xOf(cohort.score.mean)} y={top - 10} textAnchor="middle" fontSize={10.5} fontFamily={FONT} fontWeight={700} fill={ORANGE}>
            {`mean ${fmt(cohort.score.mean)}`}
          </text>
        </g>
        <g>
          <path d={`M${xOf(1_000_000)},${top - 40} V${top + stripH + 6}`} stroke={ACCENT} strokeWidth={1.5} strokeDasharray="4 4" />
          <text x={xOf(1_000_000)} y={top - 44} textAnchor="end" fontSize={10.5} fontFamily={FONT} fontWeight={700} fill={ACCENT}>
            the one-million target
          </text>
        </g>

        <text x={left} y={top + stripH + 48} fontSize={11} fontFamily={FONT} fill={INK_2}>
          {`Half the games finished below ${fmt(cohort.score.median)}. The single best game reached ${fmt(cohort.score.max)} — and the average is ${fmt(cohort.score.mean)}.`}
        </text>
        <text x={left} y={top + stripH + 66} fontSize={11} fontFamily={FONT} fill={INK_3}>
          {`Lowest game ${fmt(cohort.score.min)} · lower quartile ${fmt(cohort.score.q25)} · standard deviation ${fmt(cohort.score.sd)}`}
        </text>
      </svg>
      <details className="engine-table">
        <summary>table view — the recorded cohort summary</summary>
        <table>
          <thead>
            <tr>
              <th>quantity</th>
              <th>score</th>
              <th>moves</th>
            </tr>
          </thead>
          <tbody>
            <tr><td>mean</td><td>{cohort.score.mean.toLocaleString("en-US")}</td><td>{cohort.moves.mean}</td></tr>
            <tr><td>median</td><td>{cohort.score.median.toLocaleString("en-US")}</td><td>{cohort.moves.median}</td></tr>
            <tr><td>lower quartile</td><td>{cohort.score.q25.toLocaleString("en-US")}</td><td>{cohort.moves.q25}</td></tr>
            <tr><td>minimum</td><td>{cohort.score.min.toLocaleString("en-US")}</td><td>{cohort.moves.min}</td></tr>
            <tr><td>maximum</td><td>{cohort.score.max.toLocaleString("en-US")}</td><td>{cohort.moves.max}</td></tr>
            <tr><td>standard deviation</td><td>{cohort.score.sd.toLocaleString("en-US")}</td><td>—</td></tr>
          </tbody>
        </table>
      </details>
      {caption && <figcaption>{caption}</figcaption>}
    </figure>
  );
}

/* =========================================================================
 * 8. What a handful of games can say, and what it cannot.
 * ========================================================================= */

export function CohortScale({
  points,
  target = 1_000_000,
  caption,
}: {
  /** Each recorded figure the page quotes, with its own evidence label. */
  points: {
    label: string;
    value: number;
    /** The figure exactly as the record writes it, when that differs from the plotted value. */
    display?: string;
    evidence: string;
    tone?: "reference" | "anecdote" | "target";
  }[];
  target?: number;
  caption?: string;
}) {
  const W = 760;
  const rowH = 50;
  const H = 60 + points.length * rowH;
  const left = 282;
  const right = 92;
  const plotW = W - left - right;
  const scale = Math.max(target, ...points.map((p) => p.value)) * 1.08;
  const xOf = (value: number) => left + (value / scale) * plotW;
  const toneColor = { reference: BLUE, anecdote: INK_3, target: ACCENT };
  return (
    <figure className="engine-fig">
      <svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Recorded scores against the one-million target">
        <text y={12} fontSize={12.5} fontFamily={FONT} fontWeight={700} fill={INK}>
          Every recorded figure, on the same axis as the target
        </text>
        <path d={`M${xOf(target)},28 V${H - 18}`} stroke={ACCENT} strokeWidth={1.5} strokeDasharray="4 4" />
        <text x={xOf(target)} y={24} textAnchor="end" fontSize={10.5} fontFamily={FONT} fontWeight={700} fill={ACCENT}>
          {`${fmt(target)} — the qualification mean`}
        </text>
        {points.map((point, i) => {
          const color = toneColor[point.tone ?? "reference"];
          return (
            <g key={point.label} transform={`translate(0 ${36 + i * rowH})`}>
              <text x={left - 10} y={12} textAnchor="end" fontSize={11} fontFamily={FONT} fontWeight={600} fill={INK}>
                {point.label}
              </text>
              {wrap(point.evidence, 46).map((line, k) => (
                <text key={k} x={left - 10} y={26 + k * 12} textAnchor="end" fontSize={9.5} fontFamily={FONT} fill={INK_3}>
                  {line}
                </text>
              ))}
              <rect x={left} y={2} width={plotW} height={16} rx={4} fill="#141418" />
              <rect x={left} y={2} width={xOf(point.value) - left} height={16} rx={4} fill={color} />
              <text x={xOf(point.value) + 8} y={14} fontSize={11} fontFamily={FONT} fontWeight={700} fill={INK}>
                {point.display ?? fmt(point.value)}
              </text>
            </g>
          );
        })}
      </svg>
      {caption && <figcaption>{caption}</figcaption>}
    </figure>
  );
}
