// Repository access for ./do-research: planning context, record creation,
// and the seed-lease allocator.  Everything here is deliberately conservative:
// the allocator refuses protected/final prefixes outright, refuses any range
// that overlaps an existing lease record or any 8-hex-digit constant already
// in the tree, and records every grant in research/seeds/leases/ and the
// lease map before a single seed can be read.

import { execFileSync, spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { randomBytes } from "node:crypto";

export const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
export const RESEARCHCTL = path.join(REPO_ROOT, ".agents/skills/million-point-research/scripts/researchctl.py");

export function isoNow(): string {
  return new Date().toISOString().replace(/\.\d{3}Z$/, "Z");
}

export function readText(relative: string, limitLines?: number): string {
  const full = path.join(REPO_ROOT, relative);
  if (!existsSync(full)) return "";
  const text = readFileSync(full, "utf8");
  if (!limitLines) return text;
  return text.split("\n").slice(0, limitLines).join("\n");
}

export function readJson<T = any>(relative: string): T | null {
  const full = path.isAbsolute(relative) ? relative : path.join(REPO_ROOT, relative);
  if (!existsSync(full)) return null;
  return JSON.parse(readFileSync(full, "utf8")) as T;
}

export function writeJson(relative: string, value: unknown): void {
  const full = path.isAbsolute(relative) ? relative : path.join(REPO_ROOT, relative);
  mkdirSync(path.dirname(full), { recursive: true });
  writeFileSync(full, JSON.stringify(value, null, 2) + "\n");
}

export function listRecords<T = any>(subdir: string): Array<T & { $path: string }> {
  const dir = path.join(REPO_ROOT, "research", subdir);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((name) => name.endsWith(".json"))
    .sort()
    .map((name) => ({ ...(readJson<T>(path.join(dir, name)) as T), $path: `research/${subdir}/${name}` }));
}

export function listFamilies(): string[] {
  return readdirSync(path.join(REPO_ROOT, "approaches"), { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
}

function mdxSummary(relative: string): string {
  const text = readText(relative);
  if (!text) return "";
  const front = text.match(/^---\n([\s\S]*?)\n---/);
  const headings = text.split("\n").filter((line) => /^#{2,3} /.test(line)).slice(0, 20);
  return `${relative}\n${front ? front[1] : ""}\n${headings.join("\n")}`;
}

export interface HistoryEntry {
  iteration: number;
  theoryId?: string;
  experimentId?: string;
  title: string;
  outcome: string;
  notes: string;
}

/** The brief the planner reads.  Only retained repository text, no numbers of our own. */
export function gatherContext(history: HistoryEntry[], focus: string | undefined): string {
  const theories = listRecords("theories").map((t) => `- ${t.theoryId}: ${t.title} [${t.lifecycle}/${t.assessment}/${t.evidenceTier}]`);
  const experiments = listRecords("experiments").map((e) => `- ${e.experimentId}: ${e.title} [${e.benchmarkTier}/${e.lifecycle}]`);
  const results = listRecords("results").map((r) => `- ${r.resultId} (${r.experimentId}): ${r.runValidity}/${r.scientificOutcome}/${r.evidenceTier} — ${String(r.summary).slice(0, 400)}`);
  const leases = listRecords("seeds/leases").map((l) => `- ${l.seedLeaseId}: ${l.rangeStartHex}-${l.rangeEndExclusiveHex} ${l.role} ${l.state}`);
  const logDir = path.join(REPO_ROOT, "web/content/log");
  const logs = existsSync(logDir) ? readdirSync(logDir).filter((n) => n.endsWith(".mdx")).sort().slice(-2) : [];
  const doctor = spawnSync("python3", [RESEARCHCTL, "doctor"], { cwd: REPO_ROOT, encoding: "utf8" });
  const parts = [
    "# Planning brief (generated by ./do-research; every line is quoted from the repository)",
    focus ? `\n## Operator focus\n${focus}` : "",
    "\n## docs/research/status.md (head)\n" + readText("docs/research/status.md", 230),
    "\n## docs/research/roadmap.md priority map\n" + readText("docs/research/roadmap.md", 60),
    "\n## Theories\n" + theories.join("\n"),
    "\n## Experiments\n" + experiments.join("\n"),
    "\n## Results\n" + results.join("\n"),
    "\n## Seed leases on record\n" + leases.join("\n"),
    "\n## Lease map (docs/exploratory/lease-map.md allocation table)\n" + readText("docs/exploratory/lease-map.md").split("\n").filter((l) => l.startsWith("|")).join("\n"),
    "\n## Recent research log entries\n" + logs.map((n) => mdxSummary(`web/content/log/${n}`)).join("\n\n"),
    "\n## Approach families\n" + listFamilies().join(", "),
    "\n## Machine (researchctl doctor)\n" + (doctor.stdout || "").slice(0, 3000),
    "\n## This orchestrator's earlier iterations\n" + (history.length ? history.map((h) => `- iteration ${h.iteration}: ${h.title} → ${h.outcome}. ${h.notes}`).join("\n") : "(none)"),
  ];
  return parts.join("\n");
}

// ---------------------------------------------------------------------------
// Seed leases
// ---------------------------------------------------------------------------

const FORBIDDEN_PREFIXES = ["0x7d", "0xd7"]; // protected and final cohorts: never allocatable

export interface LeasePool {
  startHex: string;
  endExclusiveHex: string;
}

function allKnownConstants(): Set<number> {
  // Every 8-hex-digit constant already present in the tree, as the lease map prescribes.
  const out = spawnSync("bash", ["-c", "grep -rhoE '0x[0-9a-fA-F]{8}' docs approaches src research artifacts 2>/dev/null | sort -u"], { cwd: REPO_ROOT, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
  const set = new Set<number>();
  for (const line of (out.stdout || "").split("\n")) {
    if (line) set.add(Number.parseInt(line, 16));
  }
  return set;
}

function existingLeaseRanges(): Array<[number, number]> {
  return listRecords("seeds/leases").map((l) => [Number.parseInt(l.rangeStartHex, 16), Number.parseInt(l.rangeEndExclusiveHex, 16)] as [number, number]);
}

export interface LeaseGrant {
  seedLeaseId: string;
  rangeStartHex: string;
  rangeEndExclusiveHex: string;
  role: string;
  path: string;
}

/**
 * Grants the next free block of `count` seeds from the pool, skipping any
 * seed that is an existing constant or inside an existing lease, and refuses
 * forbidden prefixes.  Writes the SL record (state reserved) and a row in the
 * lease map.  Returns null when the pool cannot satisfy the request.
 */
export function allocateLease(pool: LeasePool, count: number, role: string, experimentId: string, purpose: string): LeaseGrant | null {
  const start = Number.parseInt(pool.startHex, 16);
  const end = Number.parseInt(pool.endExclusiveHex, 16);
  for (const prefix of FORBIDDEN_PREFIXES) {
    if (pool.startHex.toLowerCase().startsWith(prefix) || pool.endExclusiveHex.toLowerCase().startsWith(prefix)) {
      throw new Error(`lease pool ${pool.startHex} touches a forbidden prefix ${prefix}`);
    }
  }
  const constants = allKnownConstants();
  const ranges = existingLeaseRanges();
  const blocked = (seed: number) => constants.has(seed) || ranges.some(([a, b]) => seed >= a && seed < b);
  // Align blocks to 256 seeds so ranges stay readable in hex.
  for (let candidate = Math.ceil(start / 256) * 256; candidate + count <= end; candidate += 256) {
    let clean = true;
    for (let seed = candidate; seed < candidate + count; seed += 1) {
      if (blocked(seed)) { clean = false; break; }
    }
    if (!clean) continue;
    const id = `SL-${isoNow().replace(/[-:]/g, "")}-${candidate.toString(16).padStart(8, "0")}`;
    const record = {
      $schema: "../schemas/seed-lease-v1.schema.json",
      format: "drop7-seed-lease-v1",
      seedLeaseId: id,
      experimentId,
      rngAlgorithm: "mulberry32 with mix32 domain separation (src/core/native/engine.hpp); headless disc stream kNextDiscDomain, reveal stream kRevealDomain",
      domain: "environment",
      role,
      rangeStartHex: `0x${candidate.toString(16).padStart(8, "0")}`,
      rangeEndExclusiveHex: `0x${(candidate + count).toString(16).padStart(8, "0")}`,
      cohortManifestSha256: null,
      state: "reserved",
      reservedAt: isoNow(),
      openedAt: null,
      closedAt: null,
      protocolSha256: null,
      runIds: [],
      notes: [
        `Allocated by scripts/do-research from pool ${pool.startHex}-${pool.endExclusiveHex} after scanning every 8-hex-digit constant under docs/, approaches/, src/, research/ and artifacts/ and every research/seeds/leases record; the block overlaps none of them and no protected (0x7d) or final (0xd7) prefix.`,
        `Purpose: ${purpose}. Once read, the role is permanent: ${role} data can never become confirmation evidence.`,
      ],
    };
    const rel = `research/seeds/leases/${id}.json`;
    writeJson(rel, record);
    appendLeaseMapRow(record.seedLeaseId, record.rangeStartHex, record.rangeEndExclusiveHex, count, role, experimentId);
    return { seedLeaseId: id, rangeStartHex: record.rangeStartHex, rangeEndExclusiveHex: record.rangeEndExclusiveHex, role, path: rel };
  }
  return null;
}

function appendLeaseMapRow(id: string, startHex: string, endHex: string, count: number, role: string, experimentId: string): void {
  const full = path.join(REPO_ROOT, "docs/exploratory/lease-map.md");
  let text = readFileSync(full, "utf8");
  const header = "## Orchestrator allocations (scripts/do-research)";
  if (!text.includes(header)) {
    text += `\n${header}\n\nEach row was written by the allocator before any seed in it was read.\n\n| Lease | Range | Games | Role | Consumer | State |\n| --- | --- | ---: | --- | --- | --- |\n`;
  }
  const endInclusive = `0x${(Number.parseInt(endHex, 16) - 1).toString(16).padStart(8, "0")}`;
  text = text.replace(/\n*$/, "\n") + `| \`${id}\` | \`${startHex}\`–\`${endInclusive}\` | ${count} | ${role} | ${experimentId} | reserved |\n`;
  writeFileSync(full, text);
}

// ---------------------------------------------------------------------------
// Records
// ---------------------------------------------------------------------------

function researchctl(args: string[]): string {
  return execFileSync("python3", [RESEARCHCTL, ...args], { cwd: REPO_ROOT, encoding: "utf8" });
}

function createdPath(output: string, prefix: string): string {
  const line = output.split("\n").map((l) => l.trim()).filter((l) => l.includes(prefix)).pop();
  if (!line) throw new Error(`researchctl did not report a ${prefix} path: ${output}`);
  return line.replace(/^created\s+/i, "").trim();
}

export function createTheory(args: { slug: string; title: string; claim: string; mechanism: string; falsification: string[]; platform: string; model: string }): { id: string; path: string } {
  const out = researchctl(["new", "theory", "--slug", args.slug, "--title", args.title, "--claim", args.claim, "--mechanism", args.mechanism, "--falsification", args.falsification[0] ?? "unspecified", "--information-class", "public-policy", "--platform", args.platform, "--model", args.model]);
  const rel = createdPath(out, "research/theories/");
  const record = readJson(rel);
  record.falsificationCriteria = args.falsification;
  record.lifecycle = "proposed";
  record.updatedAt = isoNow();
  writeJson(rel, record);
  return { id: record.theoryId, path: rel };
}

export function createExperiment(args: { slug: string; title: string; theoryId: string; hypothesis: string; candidate: string; entryPoint: string; classification: string; platform: string; model: string; patch: Record<string, unknown> }): { id: string; path: string } {
  const out = researchctl(["new", "experiment", "--slug", args.slug, "--title", args.title, "--theory-id", args.theoryId, "--hypothesis", args.hypothesis, "--candidate", args.candidate, "--entry-point", args.entryPoint, "--classification", args.classification, "--information-boundary", "public-policy", "--platform", args.platform, "--model", args.model]);
  const rel = createdPath(out, "research/experiments/");
  const record = readJson(rel);
  Object.assign(record, args.patch);
  record.updatedAt = isoNow();
  writeJson(rel, record);
  return { id: record.experimentId, path: rel };
}

export function createContribution(args: { summary: string; level: string; role: string; degree: string; platform: string; model: string; theoryId?: string; experimentId?: string; artifacts: string[]; validation: string[] }): string {
  const cli = ["new", "contribution", "--summary", args.summary, "--level", args.level, "--role", args.role, "--degree", args.degree, "--platform", args.platform, "--model", args.model];
  if (args.theoryId) cli.push("--theory-id", args.theoryId);
  if (args.experimentId) cli.push("--experiment-id", args.experimentId);
  for (const a of args.artifacts) cli.push("--artifact", a);
  for (const v of args.validation) cli.push("--validation", v);
  const out = researchctl(cli);
  const rel = createdPath(out, "research/contributions/");
  return readJson(rel).contributionId;
}

export function validateRecords(): { ok: boolean; output: string } {
  const result = spawnSync("make", ["research-validate"], { cwd: REPO_ROOT, encoding: "utf8" });
  return { ok: result.status === 0, output: (result.stdout || "") + (result.stderr || "") };
}

export function newRunId(prefix: string): string {
  return `${prefix}-${isoNow().replace(/[-:]/g, "")}-${randomBytes(4).toString("hex")}`;
}

export function gitShort(): string {
  try {
    return execFileSync("git", ["rev-parse", "--short", "HEAD"], { cwd: REPO_ROOT, encoding: "utf8" }).trim();
  } catch {
    return "unknown";
  }
}
